### ISSUE TITLE
npmjs.org doesn't link to this repo

### ISSUE THREAD

**Issue by wbeard** [cgadam/artifactory-api#2]
Hi there,

Just thought I'd let you know that your wonderful module, as listed on npmjs.org, doesn't have its github repo linked.

You might want to look into this.

Thanks,

William Beard

**Comment by iarna** [comment]
Can you elaborate on what you were expecting? When I look at:

https://www.npmjs.com/package/artifactory-api

I see, on the right hand side in the column "One open issue on Github" which links here...

**Comment by iarna** [comment]
Clarification: You expect a link to here to appear below the version # and above the license?

**Comment by cgadam** [comment]
Rebecca,

Correct.. I'm expecting something like this:
[image: Imágenes integradas 1]

But instead in the module I'm mentioning (artifactory-api) I see:

[image: Imágenes integradas 2]

So I'm not sure at this point if this is a problem with my package.json or
the npm registry not creating this link automatically.

Christian -

2015-08-18 20:08 GMT-03:00 Rebecca Turner notifications@github.com:

**Comment by iarna** [comment]
Yeah, everything looks ok _to me_, in your package.json and what's in the registry. I gather that our support team will be following up with the appropriate folks tomorrow during our regular business hours.

**Comment by cgadam** [comment]
Ok, thank you @iarna !

**Comment by cgadam** [comment]
Looks like it's related to this npm issue:
https://github.com/npm/newww/issues/1172

**Comment by aredridel** [comment]
And https://github.com/npm/newww/issues/1173 has a proposed fix.

**Comment by aredridel** [comment]
Also: if you sent images with your comments with your expectations, they didn't make it on to the issue.

**Comment by cgadam** [comment]
Thanks for referencing the other issue as well @aredridel !
The comment was added automatically to the issue when I replied to the support agent via email. So I guess support agents at least got the screenshot. Anyway, it is exactly what she described.

**Comment by aredridel** [comment]
Excellent.

**Comment by iarna** [comment]
@cagadam: Who me? I didn't see those images either– I've only interacted with this issue via the web. (I'm not actually from support per se– just providing some cross team help. 😃)

**Comment by cgadam** [comment]
@iarna ! I got confused after receiving e-mails from this open issue and other e-mails I exchanged with npm support team which point me also to 1172. :) In any case, thanks for your collaboration!!

**Comment by cgadam** [comment]
It is working now :)
